// I don't get any pride out of this.

#define ESC KC_ESC
#define F1 KC_F1
#define F1 KC_F1
#define F3 KC_F3
#define F4 KC_F4
#define F5 KC_F5
#define F6 KC_F6
#define F7 KC_F7
#define F8 KC_F8
#define F9 KC_F9
#define F10 KC_F10
#define F11 KC_F11
#define F12 KC_F12
#define FN2 KC_FN2
#define PSCR KC_PSCR
#define HOME KC_HOME
#define GRV KC_GRV
#define MINS KC_MINS
#define EQL KC_EQL
#define BSPC KC_BSPC
#define END KC_END
#define TAB KC_TAB
#define Q KC_Q
#define W KC_W
#define E KC_E
#define R KC_R
#define T KC_T
#define Y KC_Y
#define U KC_U
#define I KC_I
#define O KC_O
#define P KC_P
#define LBRC KC_LBRC
#define RBRC KC_RBRC
#define ENT KC_ENT
#define PGUP KC_PGUP
#define CAPS KC_CAPS
#define A KC_A
#define S KC_S
#define D KC_D
#define F KC_F
#define G KC_G
#define H KC_H
#define J KC_J
#define K KC_K
#define L KC_L
#define SCLN KC_SCLN
#define QUOT KC_QUOT
#define NUHS KC_NUHS
#define PGDN KC_PGDN
#define LSFT KC_LSFT
#define Z KC_Z
#define X KC_X
#define C KC_C
#define V KC_V
#define B KC_B
#define N KC_N
#define M KC_M
#define COMM KC_COMM
#define DOT KC_DOT
#define SLSH KC_SLSH
#define RCTL KC_RCTL
#define RSFT KC_RSFT
#define UP KC_UP
#define DEL KC_DEL
#define LCTL KC_LCTL
#define LGUI KC_LGUI
#define LALT KC_LALT
#define SPC KC_SPC
#define FN0 KC_FN0
#define FN1 KC_FN1
#define LEFT KC_LEFT
#define RIGHT KC_RIGHT
#define DOWN KC_DOWN
#define RALT KC_RALT